# Operators and states

In [4]:
# file: seeq/operators.py
import numpy as np
import scipy.sparse as sp

## Spin models

In [5]:
# file: seeq/operators.py

σx = sp.csr_matrix([[0.0,1.0],[1.0,0.0]])
σz = sp.csr_matrix([[1.0,0.0],[0.0,-1.0]])
σy = sp.csr_matrix([[0.0,-1.j],[1.j,0.0]])

## Fock operators

In [6]:
# file: seeq/operators.py

def boson_creation(nmax, format='csr'):
    ad = np.sqrt(np.arange(1., nmax))
    if format == 'dense':
        return np.diag(ad, -1)
    else:
        return sp.diags(ad, -1, format=format)

In [33]:
# file: seeq/operators.py

def boson_anihilation(nmax, format='csr'):
    a = np.sqrt(np.arange(1., nmax))
    if format == 'dense':
        return np.diag(a, +1)
    else:
        return sp.diags(a, +1, format=format)

In [8]:
# file: seeq/operators.py

def boson_number(nmax, format='csr'):
    n = np.arange(0., nmax)
    if format == 'dense':
        return np.diag(0, +1)
    else:
        return sp.diags(n, 0, format=format)

## Tests

In [ ]:
# file: seeq/test/test_parametric_control.py

import numpy as np
import scipy.sparse as sp
from seeq.states import *

In [15]:
import numpy as np
import scipy.sparse as sp


In [44]:
# file: seeq/test/test_operators.py

import unittest

class TestOperators(unittest.TestCase):
    
    @staticmethod
    def commute(x, y):
        return x @ y - y @ x
    
    def assertEqualMatrix(self, a, b):
        if sp.issparse(a):
            a = a.todense()
        if sp.issparse(b):
            b = b.todense()
        if (a.s)
        if (a == b).all():
            return True
        raise self.failureException(f'Matrices not equal:\na={a}\nb={b}')

    def test_commutation_Pauli(self):
        """For a qubit to remain the same, we do nothing."""
        for (a, b, c) in [(σx, σy, 2.j*σz)]:
            self.assertEqualMatrix(self.commute(σx, σy), 2j*σz)
            self.assertEqualMatrix(self.commute(σy, σz), 2j*σx)
            self.assertEqualMatrix(self.commute(σz, σx), 2j*σy)

    def test_boson_creation(self):
        """For a qubit to remain the same, we do nothing."""
        a2 = np.array([[0,1.0],
                       [0,0]])
        n2 = np.array([[0,0],[0,1]])
        self.assertEqualMatrix(boson_creation(2), a2.T)
        self.assertEqualMatrix(boson_anihilation(2), a2)
        self.assertEqualMatrix(boson_number(2), n2)
        
        a3 = np.array([[0,1.0,0],
                       [0,0,np.sqrt(2.)],
                       [0,0,0]])
        n3 = np.array([[0,0,0],[0,1.,0],[0,0,2.]])
        self.assertEqualMatrix(boson_creation(3), a3.T)
        self.assertEqualMatrix(boson_anihilation(3), a3)
        self.assertEqualMatrix(boson_number(3), n3)
        
        a4 = np.array([[0,1.0,0,0],
                       [0,0,np.sqrt(2.),0],
                       [0,0,0,np.sqrt(3.)],
                       [0,0,0,0]])
        n4 = np.array([[0,0,0,0],[0,1.,0,0],[0,0,2.,0],[0,0,0,3.]])
        self.assertEqualMatrix(boson_creation(4), a4.T)
        self.assertEqualMatrix(boson_anihilation(4), a4)
        self.assertEqualMatrix(boson_number(4), n4)

In [45]:
suite1 = unittest.TestLoader().loadTestsFromNames(['__main__.TestOperators'])
unittest.TextTestRunner(verbosity=2).run(suite1);

test_boson_creation (__main__.TestOperators)
For a qubit to remain the same, we do nothing. ... C:\Users\JuanJose\Miniconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
C:\Users\JuanJose\Miniconda3\lib\site-packages\ipykernel_launcher.py:19: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
ERROR
test_commutation_Pauli (__main__.TestOperators)
For a qubit to remain the same, we do nothing. ... 

[[0. 0.]
 [1. 0.]]
[[0. 0.]
 [1. 0.]]
[[ True  True]
 [ True  True]]
[[0. 1.]
 [0. 0.]]
[[0. 1.]
 [0. 0.]]
[[ True  True]
 [ True  True]]
[[0. 0.]
 [0. 1.]]
[[0 0]
 [0 1]]
[[ True  True]
 [ True  True]]
[[0.         0.         0.        ]
 [1.         0.         0.        ]
 [0.         1.41421356 0.        ]]
[[0.         0.         0.        ]
 [1.         0.         0.        ]
 [0.         1.41421356 0.        ]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[0.         1.         0.        ]
 [0.         0.         1.41421356]
 [0.         0.         0.        ]]
[[0.         1.         0.        ]
 [0.         0.         1.41421356]
 [0.         0.         0.        ]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[0.         0.         0.         0.        ]
 [1.         0.         0.         0.        ]
 

ok

ERROR: test_boson_creation (__main__.TestOperators)
For a qubit to remain the same, we do nothing.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-44-16db822336c8>", line 52, in test_boson_creation
    self.assertEqualMatrix(boson_creation(4), a3.T)
  File "<ipython-input-44-16db822336c8>", line 19, in assertEqualMatrix
    if (a == b).all():
AttributeError: 'bool' object has no attribute 'all'

----------------------------------------------------------------------
Ran 2 tests in 0.021s

FAILED (errors=1)


In [20]:
(np.zeros((2,2)) == np.ones((2,2))).all()

False

In [24]:
boson_creation(2) == np.array([[0,1.0,0],
                        [0,0,np.sqrt(2.)],
                        [0,0,0]])

False

In [28]:
boson_creation(2).todense()

matrix([[0., 0.],
        [1., 0.]])